### ISSUE TITLE
Global Middleware Loader Consumes Errors

### ISSUE THREAD

**Issue by jmrieger** [quickenloans-mcp/mcp-panthor#26] opened 2018-01-03 22:27 UTC
https://github.com/quickenloans-mcp/mcp-panthor/blob/master/src/Bootstrap/GlobalMiddlewareLoader.php#L64

If there's an issue with loading some dependent services used in the constructor for a global middleware, that error gets gobbled up by the try-catch here as failing to retrieve the global middleware.

Would it be possible to throw the 'Failed to retrieve...' error if it's not present in the DI, i.e.:
```
if ($this->di->has($name)) {
    return $this->di->get($name);
}
$msg = sprintf('Failed to retrieve global middleware "%s" from DI container.', $name);
throw new Exception($msg, $e->getCode(), $e);
```

I can submit a PR for it, but wanted to check first to see if there was a specific design decision around this feature.

**Comment by skluck** [comment] 2018-01-04 21:59
This is intended behavior, it catches any exceptions and then rethrows them. The original exception is attached to the new library exception.

It's a pretty common practice to try to ensure any exceptions thrown by a library use a common exception type. This makes it easier to detect, catch, or handle by users of the libraries.

There are pros and cons to that, so it's not necessarily used everywhere. The exception is not being suppressed, it's just wrapped in another. Your error handler should still be reporting it correctly.

What behavior are you expecting that you are not getting?

**Comment by jmrieger** [comment] 2018-02-01 22:48
I expect that the error thrown, which isn't handled or otherwise processed by this framework, is allowed to bubble up.

**Comment by skluck** [comment] 2018-03-12 21:41
Sorry, this is my bad for not following up in a more timely manner.

I'm going to close this. There are few ways for you to customize the behavior if you don't like it:

1. Just copy the class and use your own version. It's pretty simple class so easy to do.
2. Extend the class, catch and and unwrap the exceptions if any are thrown.
3. Modify the error handler to unwrap exceptions in a different way (e.g. inspect the first exception/message and chop it off if it matches).

1 is probably the easiest. To be honest I've never actually run into this situation outside of dev. I know why it occurs in your situation (failure of getting runtime configuration), but honestly we should probably be handling that in a different way inside of the runtime config lib instead of letting it fail all the way through the framework.

**Closed by skluck** 2018-03-12 21:41 UTC
